export default [
    {
        name: "burgie kong",
        screenName: "aram_miquel",
        avatar: "https://i.redd.it/s4krqgtwnxa71.jpg",
        id: "1",
        lastmsg: "hola",
        time: "gettime",
        fullText:"Buenas",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 1,
        gameuri: "https://cdn2.unrealengine.com/ecosystem-w-fn-1920x1080-ac7f3aa4b57b.jpg",
        namegame: "Fortnite"
    },
    {
        name: "Nose",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "2",
        lastmsg: "hola",
        time: "gettime",
        fullText:"Buenas gente",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 2,
        gameuri: "https://pbs.twimg.com/profile_images/1359301269266038785/-U4xyBGU_200x200.jpg",
        namegame: "Call of Gruty"
    },
    {
        name: "Ekizde",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "3",
        lastmsg: "hola",
        time: "gettime",
        fullText:"Que pasioo",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 3,
        gameuri: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/3241660/2cff5912c1add2e009eb1c1c630a47ac06cb81a1/capsule_616x353.jpg?t=1747381002",
        namegame: "R.E.P.O"
    },
    {
        name: "Jijijija",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "4",
        lastmsg: "hola",
        time: "gettime",
        fullText:"a mimir",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 4,
        gameuri: "https://cdn.sortiraparis.com/images/80/66131/1103306-valorant-le-jeu-video-signe-riot-games-est-disponible.jpg",
        namegame: "Valorant"
    },
    {
        name: "Pro123",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "5",
        lastmsg: "hola",
        time: "gettime",
        fullText:"huenas gente",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 1,
        gameuri: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/CNTWUAMXZRF3BPIYPCNPFHOMJQ.jpg",
        namegame: "League of Legends"
    },

]
