export default [
    {
        name: "burgie kong",
        screenName: "aram_miquel",
        avatar: "https://i.redd.it/s4krqgtwnxa71.jpg",
        id: "1",
        lastmsg: "hola",
        time: "gettime",
        fullText:"Buenas",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 1,
    },
    {
        name: "Nose",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "2",
        lastmsg: "hola",
        time: "gettime",
        fullText:"Buenas gente",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 2,
    },
    {
        name: "Ekizde",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "3",
        lastmsg: "hola",
        time: "gettime",
        fullText:"Que pasioo",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 3,
    },
    {
        name: "Jijijija",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "4",
        lastmsg: "hola",
        time: "gettime",
        fullText:"a mimir",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 4,
    },
    {
        name: "Pro123",
        screenName: "aram_miquel",
        avatar: "https://images.unsplash.com/photo-1625690988276-0a7b0cdf3d5d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: "5",
        lastmsg: "hola",
        time: "gettime",
        fullText:"huenas gente",
        retweetCount: 2,
        replyCount: 1,
        likeCount: 5,
        players: 1,
    },

]
